version: 0.0.1.{build}
skip_tags: true
os: Visual Studio 2015 RC
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: 0.0.1
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\*UnitTest.dll'